name: 'Deploy Gatsby to AWS S3'
description: 'Deploy a Gatsby Project to an AWS S3 bucket (optional Cloudfront support)'
author: 'pedreviljooen'
inputs:
  build-directory:
    description: 'Your static site build directory'
    required: true
  s3-bucket-name:
    description: 'Destination S3 Bucket'
    required: true
  browser-cache-duration:
    description: 'Browser cache duration (sec) for cache control headers'
    default: '31536000'
  cdn-cache-duration:
    description: 'CDN cache duration (sec) for cache control headers (sec)'
    default: '31536000'
  cloudfront-id-to-invalidate:
    description: 'Cloudfront ID to invalidate'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'  
  color: 'orange'